name: Deploy-Prod

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version for deploy
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          DEPLOY_VERSION=$(echo "$VERSION" |tr . -).zip
          echo $DEPLOY_VERSION >> "$GITHUB_ENV"
          
          echo ${{  env.DEPLOY_VERSION  }}
