name: Deploy-Prod

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version for deploy
        run: |
          DEPLOY_VERSION=${GITHUB_REF#refs/*/}
          echo $DEPLOY_VERSION | sed 's/./-/' >> $GITHUB_ENV
          #DEPLOY_VERSION=$(echo "$VERSION" |tr . -)

          #echo $DEPLOY_VERSION>> "$GITHUB_ENV"
          echo ${{  env.DEPLOY_VERSION  }}    
